### ISSUE TITLE
.bat commands

### ISSUE THREAD

**Issue by Alkimical** [ca1e/REngine-MSG-Tool#5]
Which ones are the .bat commands, im trying some and all i get is:

```
Resident Evil msg tool.  -- by cale -- Version 2.0 -- 27.04.2023

export: re2-msg-tool.exe msg_file_01.msg.<12|14|15|17|22>
import: re2-msg-tool.exe msg_file_01.msg.<12|14|15|17|22>.txt
Press any key to continue . . .
```
With no extraction.

**Comment by ca1e** [comment]
you can open a terminal window to execute the command with a msg file as a argument

**Comment by Alkimical** [comment]
It worked but just for msg.14 and only extract in Japanese.
Any other like .12 .15 .22 cmd say:

```
Unhandled Exception: System.Exception: [Header]The file has an unknown header.
   at REngine.MsgTool.MsgFile.Check(Boolean cond, String reason) in D:\Downloads\REngine-MSG-Tool-main\REngine-MSG-Tool-main\REngine-msg-tool\ReToolMsg\MsgFile.cs:line 180
   at REngine.MsgTool.MsgFile.Read(Stream input, MsgVersion version) in D:\Downloads\REngine-MSG-Tool-main\REngine-MSG-Tool-main\REngine-msg-tool\ReToolMsg\MsgFile.cs:line 78
   at REngine_msg_tool.Program.Main(String[] args) in D:\Downloads\REngine-MSG-Tool-main\REngine-MSG-Tool-main\REngine-msg-tool\Program.cs:line 45
```
